config/routes.rb
Yearbook::Application.routes.draw do
  resources :cheers
  resources :titles
  resources :poem_pages
  resources :leaders
  resources :teachers
  resources :activities
  resources :honors
  resources :graduates
  resources :autographs
  resources :images do
    collection do
      resources :tags
    end
  end
  resources :yb_classes
  resources :days
  resources :articles
  resources :people
  resources :families

  get 'yearbook' => "titles#index"

  get 'draft' => "draft#draft"

  devise_for :users, :controllers => { registrations: "registrations", invitations: "invitations"}

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.has_role? :admin
        can :manage, :all
        can :invite, User
        can :manage, Article
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  resourcify
  def authors
    User.with_role(:author,self)
  end
end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  has_many :images, as: :imageable
end

app/models/day.rb
class Day < ActiveRecord::Base
  has_and_belongs_to_many :people

  def to_s
    name
  end
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :people
  default_scope { order('name')}
  def to_s
    name
  end
end

app/models/graduate.rb
class Graduate < ActiveRecord::Base
  belongs_to :person
end

app/models/honor.rb
class Honor < ActiveRecord::Base
  belongs_to :person
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image, :styles => {
    :medium => "300x300>", 
    :thumb => "100x100>" 
  }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def to_s
    caption || filename
  end

  def import
    fn = "public#{filename}"
    puts fn
    if File.exist? fn
      puts "exists"
      self.image = File.new(fn)
      save!
    else
      puts "no exist"
    end
  end

  def self.import_all
    find_each do |person|
      person.import
    end
  end

  def tags_s
    tags.join(', ')
  end

  def tags_s= str
    self.tags = str.split(',').collect{|s| s.strip}
  end

end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :family
  has_and_belongs_to_many :days
  default_scope { order('name')}
  has_attached_file :portrait, :styles => {
    :large => "600x800#", 
    :medium => "300x400#", 
    :thumb => "150x200#" 
  }, :default_url => "/portrait/:style/missing.png"
  validates_attachment_content_type :portrait, :content_type => /\Aimage\/.*\Z/

  def to_s
    full_name
  end

  def full_name
    "#{name} #{last}"
  end

  def img
    "/people/#{family}/#{name}.jpg"
  end

  def age
    return 0 unless born_on
    years = Date.today.year - born_on.year
    years -= 1 if born_on > Date.today.years_ago( years )
    years
  end

  def import
    fn = "public#{img}"
    puts fn
    if File.exist? fn
      puts "exists"
      self.portrait = File.new(fn)
      save!
    else
      puts "no exist"
    end
  end

  def self.import_all
    find_each do |person|
      person.import
    end
  end

end

app/models/poem_page.rb
class PoemPage < ActiveRecord::Base
  has_many :images, as: :imageable
  default_scope { order('number')}
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :person
end

app/models/title.rb
class Title < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    name || email
  end
end

app/models/yb_class.rb
class YbClass < ActiveRecord::Base
  has_many :images, as: :imageable
  default_scope { order('name')}
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
    respond_with @families
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family }
      else
        format.html { render action: 'new' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:name)
    end
end

app/helpers/cheers_helper.rb
module CheersHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/draft_helper.rb
module DraftHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/families/_family.html.haml
.family
  %h1
    = link_to family.name, family

  - family.people.each do |person|
    .person
      - if person.portrait.blank?
        %img{src: person.img}
      - else
        = image_tag person.portrait :thumb
      .name= link_me person
      .days
        (
        - person.days.each do |day|
          = link_me day
        )

app/views/families/_form.html.haml
= simple_form_for(@family) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/families/_table.html.haml
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @families.each do |family|
    %tr
      %td= family.name
      %td= link_to 'Show', family
      %td= link_to 'Edit', edit_family_path(family)
      %td= link_to 'Destroy', family, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/families/edit.html.haml
%h1 Editing family

= render 'form'

= link_to 'Show', @family
\|
= link_to 'Back', families_path

app/views/families/index.html.haml
- if can? :manage, Family
  .pull-right
    = link_to 'New Family', new_family_path
%h1 Families

- @families.each do |family|
  = render partial: "families/family", object: family

app/views/families/index.tex.erb
\section*{Families}
\addcontentsline{toc}{section}{Families}
\label{sec:Families}

<% @families.each do |family| %>
\subsection*{<%= family %>}

<% family.people.each_slice(4) do |slice| %>
\begin{figure}[H]
<% slice.each do |person| %>
    \begin{minipage}[b]{0.2\linewidth}
        \centering
        \includegraphics[width=\textwidth]{img<%= person.portrait.path(:large) %>}
        <%= person.full_name %>
    \end{minipage}
    \hspace{0.5cm}
<% end %>
\end{figure}
<% end %>

<% end %>

app/views/families/index.text.erb
<% @families.each do |family| %>
<% family.people.each do |person| %>
  <%= person.portrait.url(:large) %> img<%= person.portrait.path(:large) %>
<% end %>
<% end %>

app/views/families/index.txt.erb
<% @families.each do |family| %>
<% family.people.each do |person| %>
<% if person.portrait.present? %>
<%= person.portrait.url(:large, timestamp: false) %>
<% end %>
<% end %>
<% end %>

app/views/families/new.html.haml
%h1 New family

= render 'form'

= link_to 'Back', families_path

app/views/families/show.html.haml
.pull-right
  = link_to 'Families', families_path
  = link_to 'Edit', edit_family_path(@family)
  = link_to 'Destroy', @family, :method => :delete, :data => { :confirm => 'Are you sure?' }
= render partial: "families/family", object: @family